%% INTERACTIVE DRONE CONTROLLER GUI
% Real-time GUI for the drone altitude controller
%
% Features:
% - Adjustable reference height slider
% - Real-time plotting
% - Start/Stop/Reset controls
% - Live state display

classdef DroneControllerGUI < handle
    
    properties
        controller;
        fig;
        uipanel_control;
        uipanel_plot;
        
        % UI Controls
        slider_h_ref;
        label_h_ref;
        label_state;
        btn_start;
        btn_stop;
        btn_reset;
        
        % Timer for periodic updates
        update_timer;
        running = false;
        update_interval = 0.1;  % 100 ms
    end
    
    methods
        function obj = DroneControllerGUI(model_path)
            % Initialize GUI
            
            % Create controller
            obj.controller = DroneController(model_path);
            
            % Create figure
            obj.fig = figure('Name', 'Drone Altitude Controller GUI', ...
                             'NumberTitle', 'off', ...
                             'Position', [100 100 1400 800], ...
                             'CloseRequestFcn', @obj.on_close);
            
            % Control panel (left)
            obj.uipanel_control = uipanel('Parent', obj.fig, ...
                'Title', 'Control Panel', ...
                'Position', [0.01 0.01 0.25 0.98], ...
                'BorderType', 'line', ...
                'FontSize', 10, ...
                'FontWeight', 'bold');
            
            % Plot panel (right)
            obj.uipanel_plot = uipanel('Parent', obj.fig, ...
                'Position', [0.27 0.01 0.72 0.98], ...
                'BorderType', 'line');
            
            % Setup control panel
            obj.setup_control_panel();
            
            % Move plots to plot panel
            obj.controller.fig.Parent = obj.uipanel_plot;
            
            % Setup timer for updates
            obj.setup_timer();
        end
        
        function setup_control_panel(obj)
            % Setup controls in control panel
            
            panel = obj.uipanel_control;
            
            % Title
            uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', 'SIMPLE CONTROLLER', ...
                'Units', 'normalized', ...
                'Position', [0.05 0.95 0.9 0.03], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left');
            
            % Reference height slider
            uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', 'Reference Height (m):', ...
                'Units', 'normalized', ...
                'Position', [0.05 0.85 0.9 0.03], ...
                'FontSize', 10, ...
                'HorizontalAlignment', 'left');
            
            obj.slider_h_ref = uicontrol('Parent', panel, ...
                'Style', 'slider', ...
                'Min', 0, 'Max', 20, 'Value', 5, ...
                'Units', 'normalized', ...
                'Position', [0.05 0.80 0.9 0.03], ...
                'Callback', @obj.on_slider_h_ref);
            
            obj.label_h_ref = uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', '5.0 m', ...
                'Units', 'normalized', ...
                'Position', [0.05 0.76 0.9 0.02], ...
                'FontSize', 9);
            
            % State display
            uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', 'Current State:', ...
                'Units', 'normalized', ...
                'Position', [0.05 0.70 0.9 0.03], ...
                'FontSize', 11, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left');
            
            obj.label_state = uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', sprintf('Height: 0.00 m\nVelocity: 0.00 m/s\nControl: 0.00\nAccel: 0.00 m/s^2\nError: 0.00 m'), ...
                'Units', 'normalized', ...
                'Position', [0.05 0.55 0.9 0.13], ...
                'FontSize', 9, ...
                'HorizontalAlignment', 'left', ...
                'FontFamily', 'monospace', ...
                'BackgroundColor', [0.95 0.95 0.95]);
            
            % Control buttons
            uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', 'Control:', ...
                'Units', 'normalized', ...
                'Position', [0.05 0.50 0.9 0.02], ...
                'FontSize', 10, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left');
            
            obj.btn_start = uicontrol('Parent', panel, ...
                'Style', 'pushbutton', ...
                'String', 'Start', ...
                'Units', 'normalized', ...
                'Position', [0.05 0.44 0.28 0.04], ...
                'FontSize', 10, ...
                'Callback', @obj.on_start);
            
            obj.btn_stop = uicontrol('Parent', panel, ...
                'Style', 'pushbutton', ...
                'String', 'Stop', ...
                'Units', 'normalized', ...
                'Position', [0.36 0.44 0.28 0.04], ...
                'FontSize', 10, ...
                'Enable', 'off', ...
                'Callback', @obj.on_stop);
            
            obj.btn_reset = uicontrol('Parent', panel, ...
                'Style', 'pushbutton', ...
                'String', 'Reset', ...
                'Units', 'normalized', ...
                'Position', [0.67 0.44 0.28 0.04], ...
                'FontSize', 10, ...
                'Callback', @obj.on_reset);
            
            % Info
            info_text = sprintf(['CONTROLLER INFO:\n', ...
                '• Algorithm: PID + Feedforward\n', ...
                '• kp = 0.40 (proportional)\n', ...
                '• ki = 0.12 (integral)\n', ...
                '• kd = 0.15 (derivative)\n', ...
                '• u_hover = 0.70 (equilibrium)\n', ...
                '\n', ...
                'RANGES:\n', ...
                '• Control: [-1.0, 1.0]\n', ...
                '• Reference: [0, 20] m\n', ...
                '• Sampling: 20 Hz (50 ms)']);
            
            uicontrol('Parent', panel, ...
                'Style', 'text', ...
                'String', info_text, ...
                'Units', 'normalized', ...
                'Position', [0.05 0.05 0.9 0.36], ...
                'FontSize', 8, ...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'top', ...
                'BackgroundColor', [0.90 0.95 1.0]);
        end
        
        function setup_timer(obj)
            % Setup timer for periodic updates
            
            obj.update_timer = timer('ExecutionMode', 'fixedRate', ...
                'Period', obj.update_interval, ...
                'TimerFcn', @obj.on_timer_tick, ...
                'StopFcn', @obj.on_timer_stop);
        end
        
        function on_slider_h_ref(obj, ~, ~)
            % Slider callback
            
            h_ref = get(obj.slider_h_ref, 'Value');
            obj.controller.h_ref = h_ref;
            set(obj.label_h_ref, 'String', sprintf('%.1f m', h_ref));
        end
        
        function on_start(obj, ~, ~)
            % Start button callback
            
            if obj.running
                return;
            end
            
            obj.running = true;
            set(obj.btn_start, 'Enable', 'off');
            set(obj.btn_stop, 'Enable', 'on');
            
            % Start update timer
            start(obj.update_timer);
            
            fprintf('Controller started\n');
        end
        
        function on_stop(obj, ~, ~)
            % Stop button callback
            
            obj.running = false;
            set(obj.btn_start, 'Enable', 'on');
            set(obj.btn_stop, 'Enable', 'off');
            
            % Stop update timer
            stop(obj.update_timer);
            
            fprintf('Controller stopped\n');
        end
        
        function on_reset(obj, ~, ~)
            % Reset button callback
            
            obj.on_stop([], []);
            obj.controller.reset();
            obj.controller.create_plots();
            obj.controller.fig.Parent = obj.uipanel_plot;
            
            fprintf('Controller reset\n');
        end
        
        function on_timer_tick(obj, ~, ~)
            % Timer callback for periodic updates
            
            if ~obj.running
                return;
            end
            
            % Run one control step
            u_new = obj.controller.compute_control(obj.controller.h, ...
                obj.controller.v, obj.controller.h_ref);
            
            obj.controller.u = 0.8 * obj.controller.u + 0.2 * u_new;
            
            % Predict acceleration
            a = obj.controller.predict_acceleration(obj.controller.u);
            
            % Update state
            h_new = obj.controller.h + obj.controller.v * obj.controller.DT + ...
                    0.5 * a * obj.controller.DT^2;
            v_new = obj.controller.v + a * obj.controller.DT;
            
            % Safety
            if h_new < 0
                h_new = 0.0;
                v_new = max(v_new, 0.0);
            end
            
            obj.controller.h = h_new;
            obj.controller.v = v_new;
            
            % Store history
            obj.controller.time_history = [obj.controller.time_history; obj.controller.current_time];
            obj.controller.h_history = [obj.controller.h_history; obj.controller.h];
            obj.controller.v_history = [obj.controller.v_history; obj.controller.v];
            obj.controller.h_ref_history = [obj.controller.h_ref_history; obj.controller.h_ref];
            obj.controller.u_history = [obj.controller.u_history; obj.controller.u];
            obj.controller.a_history = [obj.controller.a_history; a];
            
            obj.controller.current_time = obj.controller.current_time + obj.controller.DT;
            
            % Update display every 2 ticks (200 ms)
            if mod(length(obj.controller.time_history), 2) == 0
                obj.update_state_display();
                obj.controller.update_plots();
            end
        end
        
        function update_state_display(obj)
            % Update state label
            
            error = obj.controller.h_ref - obj.controller.h;
            a_current = 0;
            if ~isempty(obj.controller.a_history)
                a_current = obj.controller.a_history(end);
            end
            
            state_str = sprintf(['Height: %.2f m\n', ...
                'Velocity: %.2f m/s\n', ...
                'Control: %+.2f\n', ...
                'Accel: %.2f m/s^2\n', ...
                'Error: %.2f m'], ...
                obj.controller.h, ...
                obj.controller.v, ...
                obj.controller.u, ...
                a_current, ...
                error);
            
            set(obj.label_state, 'String', state_str);
        end
        
        function on_timer_stop(obj, ~, ~)
            % Timer stop callback
        end
        
        function on_close(obj, ~, ~)
            % Figure close callback
            
            if isvalid(obj.update_timer)
                stop(obj.update_timer);
                delete(obj.update_timer);
            end
            
            delete(obj.fig);
        end
    end
end

%% Main execution
fprintf('Starting Drone Controller GUI...\n');
gui = DroneControllerGUI('./lstm_acceleration_model.h5');
